apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: oyfc49iwi-python 
  janus-idp.io/tekton: oyfc49iwi-python
  backstage.io/kubernetes-id: oyfc49iwi-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: oyfc49iwi-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  