apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: oyfc49iwi-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: oyfc49iwi-python 
  name: oyfc49iwi-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: oyfc49iwi-python 
